version: 1.0.{build}
environment:
  AVRAW: https://raw.githubusercontent.com/appveyor/ci/master/scripts/
  AVFILE: enable-desktop.ps1
  pyFTP: https://www.python.org/ftp/python/
  KVMASTER: 1.11.0
  LATESTPY2: 2.7.13
  LATESTPY34: 3.4.4
  LATESTPY35: 3.5.3
  LATESTPY36: 3.6.5

  matrix:
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 1
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 1
    SHORTCUTS: 0
  - PY: 27
    ARCH: 86
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 1

  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 1
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 1
    SHORTCUTS: 0
  - PY: 27
    ARCH: 64
    MASTER: 0
    ADMIN: 0
    DESIGNER: 0
    SHORTCUTS: 1

  - PY: 34
    ARCH: 86
    MASTER: 0
    ADMIN: 0
  - PY: 34
    ARCH: 86
    MASTER: 1
    ADMIN: 0

  - PY: 34
    ARCH: 64
    MASTER: 0
    ADMIN: 0
  - PY: 34
    ARCH: 64
    MASTER: 1
    ADMIN: 0

  - PY: 35
    ARCH: 86
    MASTER: 1
    ADMIN: 0
  - PY: 35
    ARCH: 86
    MASTER: 1
    ADMIN: 1

  - PY: 35
    ARCH: 64
    MASTER: 1
    ADMIN: 0
  - PY: 35
    ARCH: 64
    MASTER: 1
    ADMIN: 1

  - PY: 36
    ARCH: 86
    MASTER: 1
    ADMIN: 0
  - PY: 36
    ARCH: 86
    MASTER: 1
    ADMIN: 1

  - PY: 36
    ARCH: 64
    MASTER: 1
    ADMIN: 0
  - PY: 36
    ARCH: 64
    MASTER: 1
    ADMIN: 1

install:
- ps: iex ((new-object net.webclient).DownloadString($env:AVRAW+$env:AVFILE))

build_script:
- cmd:
    setlocal ENABLEDELAYEDEXPANSION

    REM ***********************************************************************
    REM Check vars for environment generation first, raise error if not def.  *
    REM ***********************************************************************

    if not defined PY (echo Set env var "PY" to -> 27, 34, 35, 36, 37 & exit 1)

    if not defined ARCH (echo Set env var "ARCH" to -> 86, 64 & exit 1)

    echo Py %PY%, arch %ARCH%, master %MASTER% admin %ADMIN%
    designer %DESIGNER%, shortcuts %SHORTCUTS%, cd %CD%

    REM ***********************************************************************
    REM Uninstall global Python pre-installed by Appveyor                     *
    REM versions www.appveyor.com/docs/build-environment/#python              *
    REM ***********************************************************************

    if "%ADMIN%"=="1" (
        if "%PY%"=="35" (
            if "%ARCH%"=="86" (
                bitsadmin.exe /transfer "3586" ^
                "%pyFTP%%LATESTPY35%/python-%LATESTPY35%.exe" ^
                "%cd%\py%LATESTPY35%.exe" &
                "%cd%\py%LATESTPY35%.exe" /uninstall /quiet
            ) else if "%ARCH%"=="64" (
                bitsadmin.exe /transfer "3564" ^
                "%pyFTP%%LATESTPY35%/python-%LATESTPY35%-amd64.exe" ^
                "%cd%\py%LATESTPY35%-amd64.exe" &
                "%cd%\py%LATESTPY35%-amd64.exe" /uninstall /quiet
            )
        ) else if "%PY%"=="36" (
            if "%ARCH%"=="86" (
                bitsadmin.exe /transfer "3686" ^
                "%pyFTP%%LATESTPY36%/python-%LATESTPY36%.exe" ^
                "%cd%\py%LATESTPY36%.exe" &
                "%cd%\py%LATESTPY36%.exe" /uninstall /quiet
            ) else if "%ARCH%"=="64" (
                bitsadmin.exe /transfer "3664" ^
                "%pyFTP%%LATESTPY36%/python-%LATESTPY36%-amd64.exe" ^
                "%cd%\py%LATESTPY36%-amd64.exe" &
                "%cd%\py%LATESTPY36%-amd64.exe" /uninstall /quiet
            )
        )
    )

    del "%cd%\py*.exe"

    REM ***********************************************************************
    REM Downgrade versions in kivy.bat manually for batupdate test later.     *
    REM                                                                       *
    REM Appveyor/Yaml file raises errors when a single colon (:) or two       *
    REM colons with a space are present in the file, thus EXIT as its env var *
    REM %=ExitCodeAscii% converts the int to char.                            *
    REM                                                                       *
    REM Batch knows no float math, therefore VBS (or PS) needs to be used,    *
    REM however, it may return a comma (,) instead of a period (.) in the     *
    REM result, thus convert'n'replace behavior is unfortunately necessary.   *
    REM ***********************************************************************

    kivy version > _ver

    set /p new_ver=<_ver && del _ver && set up_com=::Version

    cmd /c exit 58 & call echo %=ExitCodeAscii% > _colon

    set /p colon=<_colon & del _colon && set up_com=%up_com%%colon% %new_ver%

    set up_ver=set installerversion=%new_ver%

    echo Wscript.Echo Replace(CStr(FormatNumber(%new_ver%-0.1, 1)), ",", ".") > _calc.vbs

    cscript //Nologo _calc.vbs > _calc

    set /p old_ver=<_calc && del _calc && del _calc.vbs

    for /F "delims=" %%l in (%cd%\kivy.bat) do (if "%%l"=="%up_com%" (
        echo ::Version%colon% %old_ver%>> old.bat
    ) else if "%%l"=="%up_ver%" (
        echo set installerversion=%old_ver%>> old.bat
    ) else (echo %%l>> old.bat))

    del %cd%\kivy.bat && move %cd%\old.bat %cd%\kivy.bat

    REM ***********************************************************************
    REM Enable ECHO with DEBUG option.                                        *
    REM Set options from the env vars provided in matrix + default fallback.  *
    REM ***********************************************************************

    set DEBUG=1&& set choice_python=3&&set ___=

    if "%PY%"=="27" (
        set choice_python=2&& set py2=%LATESTPY2%&& set cp2=cp27&&set ___=
    ) else if "%PY%"=="34" (
        set py3=%LATESTPY34%&& set cp3=cp34&&set ___=
    ) else if "%PY%"=="35" (
        set py3=%LATESTPY35%&& set cp3=cp35&&set ___=
    ) else if "%PY%"=="36" (
        set py3=%LATESTPY36%&& set cp3=cp36&&set ___=
    )

    set choice_kivy=y&& set choice_master=n&&set ___=

    if "%MASTER%"=="1" (
        set choice_master=y&&set ___=
    )

    set choice_privileges=n&&set ___=

    if "%ADMIN%"=="1" (
        set choice_privileges=y&&set ___=
    )

    set choice_dsgn=n&&set ___=

    if "%DESIGNER%"=="1" (
        set choice_dsgn=y&&set ___=
    )

    set choice_shrt=n&&set ___=

    if "%SHORTCUTS%"=="1" (
        set choice_shrt=y&&set ___=
    )

    set master=%KVMASTER%&& set choice_ext=n&& set choice_gst=n&&set ___=

    REM ***********************************************************************
    REM ARCH option is the first asked option, therefore it needs a user      *
    REM interaction - handled by ECHOing through PIPE. The rest of "set /p"   *
    REM options are silenced by this step + variables are set before ECHO.    *
    REM                                                                       *
    REM The ECHO runs the kivy.bat script that doesn't need any form of user  *
    REM interaction + DEBUG in the env forbids running the Touchtracer.       *
    REM                                                                       *
    REM (echoPset /p ___="y")P form sets a value without a newline from ECHO  *
    REM ***********************************************************************

    if "%ARCH%"=="86" (
        (echo|set /p ___="y")|kivy.bat
    ) else if "%ARCH%"=="64" (
        (echo|set /p ___="n")|kivy.bat
    )

    REM ***********************************************************************
    REM Check if Python was (re)installed correctly from kivy.bat.            *
    REM ***********************************************************************

    if not exist "%cd%\python.exe" (exit /B 1)

    REM ***********************************************************************
    REM Check kivy.bat launcher in Quick Launch and SendTo folders + print.   *
    REM ***********************************************************************

    set QL=%appdata%\Microsoft\Internet Explorer\Quick Launch

    set ST=%appdata%\Microsoft\Windows\SendTo

    dir "%QL%"

    if "%SHORTCUTS%"=="1" (
        if not exist "%QL%\Kivy%PY%.bat" exit /B 1
    )

    dir "%ST%"

    if "%SHORTCUTS%"=="1" (
        if not exist "%ST%\Kivy%PY%.bat" exit /B 1
    )

    REM ***********************************************************************
    REM Output the configuration for script (for manual check if neccessary). *
    REM ***********************************************************************

    echo Installer config

    type %cd%\config.kivyinstaller

    REM ***********************************************************************
    REM Test script update command via script variable check.                 *
    REM ***********************************************************************

    kivy batupdate

    kivy version > _ver && set /p new_ver=<_ver && del _ver

    if not %new_ver% gtr %old_ver% ( exit 1 )

    dir "%cd%"
